services:
  app:
    build:
      context: .
    image: backend-sample-golang:latest
    container_name: backend-sample-golang
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: my_database

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: